### ISSUE TITLE
Question about weapons variants

### ISSUE THREAD

**Issue by cacapis** [NaridaL/mea#4]
Hi, I would like to add the new weapon variants if that's ok. Would you prefer all the weapons in the same category:
```
AR	Cln	1	CYCLONE
AR	ClnB	1	CYCLONE (BULWARK)
AR	ClnC	1	CYCLONE (CONCUSSIVE)
AR	ClnS	1	CYCLONE (SIPHON)
```
Or add 4 new categories in out/main.js

`const cats = { AR: 'Assault Rifles', ARV: 'AR Variants', P: 'Pistols', PV: 'Pistols Variants', SG: 'Shotguns', SGV: 'Shotguns Variants', SR: 'Sniper Rifles', SRV: 'SR Variants' };`

And add the weapon variants in the new categories?

```
ARV	ClnB	1	CYCLONE (BULWARK)
ARV	ClnC	1	CYCLONE (CONCUSSIVE)
ARV	ClnS	1	CYCLONE (SIPHON)
```

Thanks a lot.-

**Comment by NaridaL** [comment]
I don't think new categories are necessary, the new weapons seem to behave like standard weapons. I copied the values you pasted in, thanks!

**Comment by NaridaL** [comment]
And I just noticed Cyclone isn't the only weapon with variants. A PR with the other ones would be appreciated!
